---
- name: Install and configure caddy
  hosts: dev
  become: true
  tasks:
    - name: Install caddy
      ansible.builtin.dnf:        
        name: caddy
        state: present
    - name: Upload api Caddyfile
      ansible.builtin.copy:
        src: api.caddyfile
        dest: /etc/caddy/Caddyfile.d/api.caddyfile
        owner: caddy
        group: caddy
    - name: Restart Caddy
      ansible.builtin.systemd:
        name: caddy.service
        state: restarted
