---
- name: Install node_exporter
  hosts: all
  become: true
  vars:
    node_exporter_web_listen_address: 127.0.0.1:9100
  roles:
    - prometheus.prometheus.node_exporter
- name: Install prometheus on nova
  hosts: dev
  become: true
  vars:
    prometheus_scrape_configs:      
    - job_name: "prometheus exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
    - job_name: "node exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets:
          - "127.0.0.1:9100"
#          - "https://node_exporter.primary.faefox.dev"
  
