---
- name: Install node_exporter
  hosts: all
  become: true
  vars:
    node_exporter_web_listen_address: 127.0.0.1:9100
  roles:
    - prometheus.prometheus.node_exporter
- name: Install prometheus on nova
  hosts: dev
  become: true
  vars:
    prometheus_web_listen_address: 127.0.0.1:9999
  vars_files:
    - "vars/monitoring.yaml"
  roles:
    - prometheus.prometheus.prometheus

- name: Install grafana on nova
  hosts: dev
  become: true
  vars_files:
    - "vars/password.yaml"
  roles:
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
          admin_user: "{{ vault_admin_grafana_username }}"
          admin_password: "{{ vault_admin_grafana_password }}"

        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://127.0.0.1:9999'
            basicAuth: false
        grafana_dashboards:
          - dashboard_id: 1860
            revision_id: 40
            datasource: prometheus
- name: Install and Configure Caddy
  ansible.builtin.import_playbook: caddy.yaml
