---
- name: Install and Configure Postgresql
  import_playbook: postgresql.yaml

- name: Install and Configure API
  import_playbook: api.yaml

- name: Install and Configure Caddy
  ansible.builtin.import_playbook: caddy.yaml
