---
- name: Install node_exporter
  hosts: all
  become: true
  vars:
    node_exporter_web_listen_address: 127.0.0.1:9100
  roles:
    - prometheus.prometheus.node_exporter
- name: Install psql_exporter
  hosts: dev
  become: true
  vars_files:
    - "vars/password.yaml"
  vars:
    postgres_exporter_username: agenda
    postgres_exporter_password: "{{ vault_pgsql_agenda_user_password }}"
    postgres_exporter_name: ""
    postgres_exporter_uri: "localhost:5432/agenda?sslmode=disable"
  roles:
    - prometheus.prometheus.postgres_exporter
- name: Install prometheus on nova
  hosts: dev
  become: true
  vars:
    prometheus_web_listen_address: 127.0.0.1:9999
  vars_files:
    - "vars/monitoring.yaml"
  roles:
    - prometheus.prometheus.prometheus

- name: Install grafana on nova
  hosts: dev
  become: true
  vars_files:
    - "vars/password.yaml"
    - "vars/monitoring.yaml"
  roles:
    - role: grafana.grafana.grafana

- name: Install and Configure Postgresql
  import_playbook: postgresql.yaml

- name: Install and Configure API
  import_playbook: api.yaml

- name: Install and Configure Caddy
  ansible.builtin.import_playbook: caddy.yaml
