roles:
  - src: git+https://github.com/vanilla-extracts/ansible-role-postgresql
    version: 4.0.1
    name: postgresql
collections:
  - name: prometheus.prometheus
    version: 0.26.2
    source: https://galaxy.ansible.com
  - name: grafana.grafana
    version: 5.6.0
