---
- name: Assertions
  ansible.builtin.import_tasks: preflight.yml
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- name: Installation
  ansible.builtin.import_tasks: install.yml
  become: true
  when:
    ( not __node_exporter_is_installed.stat.exists ) or
    ( (__node_exporter_current_version_output.stderr_lines | length > 0)
      and (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version) ) or
    ( (__node_exporter_current_version_output.stdout_lines | length > 0)
      and (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version) )
  tags:
    - node_exporter_install

- name: SElinux tasks
  ansible.builtin.import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags:
    - node_exporter_configure

- name: Configure node exporter
  ansible.builtin.import_tasks: configure.yml
  become: true
  tags:
    - node_exporter_configure

- name: Ensure node exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - node_exporter_run
    - molecule-docker-notest
