#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Function to run Podman command
run_podman() {
    podman run -tiv "$(pwd)":/usr/src/build:Z \
        -v cargo-git:/home/rust/.cargo/git \
        -v cargo-registry:/home/rust/.cargo/registry \
        rust-builder cargo "$@"
}

# Check if the first argument is "podman"
if [ "$1" = "podman" ]; then
    shift  # Remove "podman" from the arguments
    run_podman "$@"
else
    echo "Usage: cargo podman <cargo-command>"
    exit 1
fi
