name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: rust-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose

