network_adm_name: "{{ deploy.pf_prefixe }}-network-adm-{{ deploy.phase }}"
network_pub_name: "{{ deploy.pf_prefixe }}-network-pub-{{ deploy.phase }}"
network_data_name: "{{ deploy.pf_prefixe }}-network-data-{{ deploy.phase }}"

admin_ip: "{{ openstack.addresses[network_adm_name].0.addr | default('') }}"
pub_ip: "{{ openstack.addresses[network_pub_name].0.addr   | default('') }}"
data_ip: "{{ openstack.addresses[network_data_name].0.addr  | default('') }}"

ansible_python_interpreter: python3
vm_bastion: "{{ deploy.pf_prefixe }}-vm-bastion-01-{{ deploy.phase }}"
vm_api_01: "{{ deploy.pf_prefixe }}-vm-apis-01-{{ deploy.phase }}"
vm_api_02: "{{ deploy.pf_prefixe }}-vm-apis-02-{{ deploy.phase }}"
vm_api_03: "{{ deploy.pf_prefixe }}-vm-apis-03-{{ deploy.phase }}"
vm_caddy: "{{ deploy.pf_prefixe }}-vm-caddy-01-{{ deploy.phase }}"
vm_bdds_01: "{{ deploy.pf_prefixe }}-vm-bdd-01-{{ deploy.phase }}"
vm_bdds_02: "{{ deploy.pf_prefixe }}-vm-bdd-02-{{ deploy.phase }}"
vm_bdds_03: "{{ deploy.pf_prefixe }}-vm-bdd-03-{{ deploy.phase }}"
vm_etcds_01: "{{ deploy.pf_prefixe }}-vm-etcd-01-{{ deploy.phase }}"
vm_etcds_02: "{{ deploy.pf_prefixe }}-vm-etcd-02-{{ deploy.phase }}"
vm_etcds_03: "{{ deploy.pf_prefixe }}-vm-etcd-03-{{ deploy.phase }}"
vm_grafana_01: "{{ deploy.pf_prefixe }}-vm-prometheus-01-{{ deploy.phase }}"
ansible_user: "cloudadm"
vm_apis_01_pub_ip: "{{ hostvars[vm_api_01]['openstack']['addresses'][network_pub_name][0]['addr'] }}"
vm_apis_02_pub_ip: "{{ hostvars[vm_api_02]['openstack']['addresses'][network_pub_name][0]['addr'] }}"
vm_apis_03_pub_ip: "{{ hostvars[vm_api_03]['openstack']['addresses'][network_pub_name][0]['addr'] }}"
vm_grafana_pub_ip: "{{ hostvars[vm_grafana_01]['openstack']['addresses'][network_pub_name][0]['addr'] }}"
fip_publication: "{{ hostvars[vm_caddy]['openstack']['addresses'][network_pub_name][1]['addr'] }}"
vip_data: "{{ hostvars[vm_bdds_01]['openstack']['metadata']['bdd_vip'] }}"
branch: "load_balancing"
name: "{{ deploy.pf_prefixe }}"
zone: "enfip-dev-devops"

vm_bdds_01_admin_ip: "{{ hostvars[vm_bdds_01]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_bdds_02_admin_ip: "{{ hostvars[vm_bdds_02]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_bdds_03_admin_ip: "{{ hostvars[vm_bdds_03]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_etcds_01_admin_ip: "{{ hostvars[vm_etcds_01]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_etcds_02_admin_ip: "{{ hostvars[vm_etcds_02]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_etcds_03_admin_ip: "{{ hostvars[vm_etcds_03]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_bdds_01_data_ip: "{{ hostvars[vm_bdds_01]['openstack']['addresses'][network_data_name][0]['addr'] }}"
vm_bdds_02_data_ip: "{{ hostvars[vm_bdds_02]['openstack']['addresses'][network_data_name][0]['addr'] }}"
vm_bdds_03_data_ip: "{{ hostvars[vm_bdds_03]['openstack']['addresses'][network_data_name][0]['addr'] }}"
vm_api_01_admin_ip: "{{ hostvars[vm_api_01]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_api_02_admin_ip: "{{ hostvars[vm_api_02]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_api_03_admin_ip: "{{ hostvars[vm_api_03]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_bastion_admin_ip: "{{ hostvars[vm_bastion]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_grafana_admin_ip: "{{ hostvars[vm_grafana_01]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
vm_caddy_admin_ip: "{{ hostvars[vm_caddy]['openstack']['addresses'][network_adm_name][0]['addr'] }}"
