network_adm_name: "{{ deploy.pf_prefixe }}-network-adm-{{ deploy.phase }}"
network_pub_name: "{{ deploy.pf_prefixe }}-network-pub-{{ deploy.phase }}"
network_data_name: "{{ deploy.pf_prefixe }}-network-data-{{ deploy.phase }}"
ansible_python_interpreter: python3
vm_bastion: "{{ deploy.pf_prefixe }}-vm-bastion-01-{{ deploy.phase }}"
vm_api_01: "{{ deploy.pf_prefixe }}-vm-apis-01-{{ deploy.phase }}"
vm_caddy: "{{ deploy.pf_prefixe }}-vm-caddy-01-{{ deploy.phase }}"
vm_bdds_01: "{{ deploy.pf_prefixe }}-vm-bdds-01-{{ deploy.phase }}"
vm_bdds_02: "{{ deploy.pf_prefixe }}-vm-bdds-02-{{ deploy.phase }}"
ansible_user: "cloudadm"
vm_bdds_01_data_ip: "{{ hostvars[vm_bdds_01]['openstack']['addresses'][network_data_name][0]['addr'] }}"
vm_apis_01_pub_ip: "{{ hostvars[vm_api_01]['openstack']['addresses'][network_pub_name][0]['addr'] }}"
fip_publication: "{{ hostvars[vm_caddy]['openstack']['addresses'][network_pub_name][1]['addr'] }}"
