---
- name: Create monitoring data partition
  community.general.parted:
    device: "/dev/vdb"
    number: "1"
    state: present

- name: Create monitoring data filesystem
  community.general.filesystem:
    device: "/dev/vdb1"
    fstype: "{{ additional_volume_filesystem | default('xfs') }}"

- name: Create monitoring data mountpoint
  ansible.posix.mount:
    path: "{{ monitoring_dir }}"
    src: "/dev/vdb1"
    fstype: "{{ additional_volume_filesystem }}"
    state: mounted
