---
- name: Restart node_exporter
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode
    - "'molecule-docker-notest' not in ansible_skip_tags"
