---

galaxy_info:
  author: DAN/A2C
  description: keepalived
  license: ""
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - "clustering"
    - "networking"
    - "system"
    - "vrrp"
    - "vip"
    - "lvs"

dependencies: []
