---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  ansible.builtin.set_fact:
    node_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

# - name: Naive assertion of proper listen address
#   ansible.builtin.assert:
#     that:
#       - "':' in node_exporter_web_listen_address"


- name: Check if node_exporter is installed
  ansible.builtin.stat:
    path: "{{ postgres_exporter_bin_dir }}/postgres_exporter"
  register: __postgres_exporter_is_installed
  check_mode: false

- name: Gather currently installed postgres_exporter version (if any)
  ansible.builtin.command: "{{ postgres_exporter_bin_dir }}/postgres_exporter --version"
  changed_when: false
  register: __postgres_exporter_current_version_output
  check_mode: false
  when: __postgres_exporter_is_installed.stat.exists
