- name: "Install and configure caddy"
  hosts: platform_shag_caddy
  gather_facts: no 
  tasks:
    - name: install prerequisites
      become: true
      apt: name={{ item }} state=latest
      with_items:
        - acl
        - caddy
      tags:
        - packages
    - name: Copy certificate
      become: true
      ansible.builtin.copy:
        src: self-signed.pem
        dest: /etc/caddy/self-signed.pem
        owner: caddy
        group: caddy
        mode: '660'
    - name: Decrypt and copy key
      become: true
      ansible.builtin.copy:
        src: secret-key.key
        dest: /etc/caddy/self-signed.key
        owner: caddy
        group: caddy
        mode: '600'
    - name: Copy Caddyfile
      become: true
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: /etc/caddy/Caddyfile
    - name: Restart Caddy
      become: true
      ansible.builtin.systemd_service:
        name: caddy
        state: restarted
