---
- name: "Install and Configure Postgresql"
  vars:
    vm_bdds_01_data_ip: "{{ hostvars[vm_bdds_01]['openstack']['addresses'][network_data_name][0]['addr'] }}"
  hosts: platform_shag_bdds
  gather_facts: no 
  tasks:
    - name: install prerequisites
      become: true
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - python3-psycopg2
      tags:
        - packages
    - name: "Install postgresql-common package"
      become: true
      ansible.builtin.apt:
        name: postgresql-common
        state: present
    - name: "Install postgresql package"
      become: true
      ansible.builtin.apt:
        name: postgresql
        state: present
    # - name: "Set listen address if none are configured"
    #   become: true
    #   ansible.builtin.lineinfile:
    #     path: /etc/postgresql/15/main/postgresql.conf 
    #     regexp: '^#listen'
    #     line: 'listen_addresses = 0.0.0.0'
    # - name: "Set correct listen address if configured"
    #   become: true
    #   ansible.builtin.lineinfile:
    #     path: /etc/postgresql/15/main/postgresql.conf 
    #     regexp: '^listen'
    #     line: "listen_adresses = 'localhost,{{ vm_bdds_01_data_ip }}'"
    # - name: "Authorise connection from data subnetwork"
    #   become: true
    #   ansible.builtin.lineinfile:
    #     path: /etc/postgresql/15/main/pg_hba.conf 
    #     line: "host agenda  agenda  172.14.0.0/24 scram-sha-256"
    #     create: yes
    - name: "Restart Postgresql"
      become: true
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted
    # - name: "Set password for postgres database user"
    #   become: true
    #   ansible.builtin.command:
    # - name: Create agenda user, password agenda, with CREATEDB and LOGIN as flags
    #   community.postgresql.postgresql_user:
    #     name: agenda
    #     password: agenda
    #     role_attr_flags: createdb,login
    #     expires: 'infinity'
    #     login_host: 'localhost'
    #     login_password: ''
    # - name: Create agenda database owned by agenda role
    #   community.postgresql.postgresql_db:
    #     name: agenda
    #     owner: agenda
