- name: "Install postgresql on VMs"
  hosts: platform_shag_bdds_01
  become: true
  vars_files:
    - vars/postgresql.yaml
    - vars/postgresql-primary.yaml
  roles:
    - postgresql
- name: "Install postgresql on Secondary VM"
  hosts: platform_shag_bdds_02
  become: true
  vars_files:
    - vars/postgresql.yaml
    - vars/postgresql-secondary.yaml
  roles:
    - postgresql
