- name: "Create repl user"
  hosts: platform_shag_bdds
  become: true
  tasks:
    - name: Create repl user, password replication, with LOGIN and REPLICATION as flags
      become_user: postgres
      community.postgresql.postgresql_user:
        name: repl
        password: replication
        role_attr_flags: replication,login
        expires: 'infinity'
    - name: Create tables
      become_user: postgres
      ansible.builtin.copy:
        src: tables.sql
        dest: /var/lib/postgresql/tables.sql
        owner: postgres
    - name: Execute PSQL file
      become_user: postgres
      ansible.builtin.command: psql -d agenda -a -f /var/lib/postgresql/tables.sql
    - name: Grant subscription right to repl
      become_user: postgres
      ansible.builtin.command: psql -c "grant pg_create_subscription to repl;" agenda
    - name: Grant schema permissions for repl
      become_user: postgres
      community.postgresql.postgresql_privs:
        login_db: agenda
        state: present
        privs: ALL
        type: schema
        objs: public,agenda
        role: repl
    - name: Grant table permissions for repl
      become_user: postgres
      community.postgresql.postgresql_privs:
        login_db: agenda
        state: present
        privs: SELECT,INSERT,UPDATE,DELETE
        type: table
        objs: users,token,events
        schema: agenda
        roles: repl
        grant_option: true
- name: "Create publication on primary database"
  hosts: platform_shag_bdds_01
  become: true
  tasks:
    - name: "Create publication"
      community.postgresql.postgresql_publication:
        login_db: agenda
        login_password: agenda
        login_host: localhost
        name: pub_agenda
        comment: Publication
        tables_in_schema: agenda

- name: "Create subscription on secondary database"
  hosts: platform_shag_bdds_02
  become: true
  tasks:
    - name: "Create subscription"
      community.postgresql.postgresql_subscription:
        login_db: agenda
        login_password: agenda
        login_host: localhost
        name: agenda
        state: present
        publications: pub_agenda
        owner: agenda
        connparams:
          host: "{{ vm_bdds_01_data_ip }}"
          port: 5432
          user: repl
          password: replication
          dbname: agenda
        comment: Subscription
