roles:
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/base-de-donnees/postgresql
    version: v2.1.7
    name: postgresql
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/r-seau/keepalived
    version: v1.3.4
    name: keepalived
