roles:
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/base-de-donnees/postgresql
    version: v2.1.7
    name: postgresql
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/r-seau/keepalived
    version: v1.3.4
    name: keepalived
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/utilitaires/prerequis
    version: v1.0.0
    name: prerequis
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/utilitaires/hosts-aliases
    version: v1.1.2
    name: hosts-aliases
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/observability/grafana
    version: v1.3.1
    name: grafana
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/observability/prometheus
    version: v3.0.0
    name: prometheus
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/observability/node-exporter.git
    version: v1.0.13
    name: node-exporter
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/observability/postgres-exporter
    version: v1.2.0
    name: postgres-exporter
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/base-de-donnees/patroni.git
    version: v2.1.5
    name: patroni
  - src: git+https://forge.dgfip.finances.rie.gouv.fr/dgfip/si1/dan-a2c/role-ansible-dgfip/base-de-donnees/etcd.git
    version: v2.0.4
    name: etcd

