---
- name: Create the ssh config
  ansible.builtin.import_playbook: create_ssh_config.yaml
- name: Install prerequisites
  hosts: platform_shag
  become: true
  roles:
    - prerequis
    - hosts-aliases 
- name: Postgres
  ansible.builtin.import_playbook: postgresql.yaml
# - name: Install and configure the API
#   ansible.builtin.import_playbook: install_and_configure_api.yaml
# - name: Install and configure Caddy
#   ansible.builtin.import_playbook: install_and_configure_caddy.yaml
