---
- name: Create the ssh config
  ansible.builtin.import_playbook: create_ssh_config.yaml
- name: Install and configure postgresql
  ansible.builtin.import_playbook: install_and_configure_postgresql.yaml
- name: Install and configure the API
  ansible.builtin.import_playbook: install_and_configure_api.yaml
