---
# defaults file for postgres-exporter

postgres_exporter_version: 0.17.1
postgres_exporter_dbname: postgres
postgres_exporter_data_source_name: "user=postgres dbname=\
  {{ postgres_exporter_dbname }} host=/var/run/postgresql/ sslmode=disable"

postgres_exporter_listen_address: "0.0.0.0"

postgres_exporter_port: 9187

postgres_exporter_bin_dir: /usr/local/bin
postgres_exporter_system_user: postgres
postgres_exporter_system_group: postgres

dgfip_download_url: "https://nexus3.appli.dgfip/repository/prometheus_postgres_exporter"

download_retries: 2
download_delay: 2

postgres_exporter_flags_collector: ""
# postgres_exporter_flags_collector: "--collector.postmaster --collector.stat_bgwriter --collector.locks --no-collector.database_wraparound"


postgres_pg_exporter_extend_query_path: "" # si besoin de custom queries, renseigner une valeur comme "/etc/prometheus/queries", ce dossier contiendra le fichier .yml listant les queries

postgres_pg_exporter_extend_queries: |
