---
galaxy_info:
  author: cloudalchemy
  role_name: node_exporter
  description: Prometheus Node Exporter
  license: MIT
  company: none
  min_ansible_version: "2.7"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - bookworm
    - name: Rocky
      versions:
        - "all"
    - name: EL
      versions:
        - "7"
        - "8"
  galaxy_tags:
    - monitoring
    - prometheus
    - exporter
    - metrics
    - system

dependencies: []
