---
# file: roles/etcd/defaults/main.yml
cluster_token: "{{ etcd_cluster_name }}"

etcd_cluster_group_ansible: "cluster_etcd"

etcd_cluster_name: "etcd-cluster-01"
etcd_initial_cluster_state: "new"
etcd_version: "3.5.5"
etcd_volume_mntp: "/etcdata"
etcd_data_directory: "{{ etcd_volume_mntp }}/{{ etcd_cluster_name }}/data"
temp_archive_download: /var/tmp/etcd-download

etcd_root_download_url: "https://nexus3.appli.dgfip/repository/etcd"

etcd_use_ssl: false
force_install: false
