---
- name: Install node_exporter
  hosts: localhost
  become: true
  vars:
    node_exporter_web_listen_address: 127.0.0.1:9100
  roles:
    - prometheus.prometheus.node_exporter
- name: Install prometheus on nova
  hosts: localhost
  become: true
  vars:
    prometheus_web_listen_address: 127.0.0.1:9999
  vars_files:
    - "vars/monitoring.yaml"
  roles:
    - prometheus.prometheus.prometheus
- name: Install grafana on nova
  hosts: localhost
  become: true
  vars_files:
    - "vars/password.yaml"
    - "vars/monitoring.yaml"
  roles:
    - role: grafana.grafana.grafana
- name: Install caddy
  import_playbook: caddy.yaml
