[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
postgres = "0.19.10"
confy = "0.6.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

