[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-postgres = "0.7.13"
uuid = { version = "1.16.0", features = ["v4"] }
confy = "0.6.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

