---
- name: Create monitoring data partition
  community.general.parted:
    device: "{{ grafana_disk }}"
    number: "1"
    state: present

- name: Create monitoring data filesystem
  community.general.filesystem:
    device: "{{ grafana_partition }}"
    fstype: "{{ additional_volume_filesystem | default('xfs') }}"

- name: Create monitoring data mountpoint
  ansible.posix.mount:
    path: "{{ grafana_data_dir }}"
    src: "{{ grafana_partition }}"
    fstype: "{{ additional_volume_filesystem | default('xfs') }}"
    state: mounted
