---
- name: Create/Delete/Update alert notifications channels (provisioning)
  become: true
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      {{ grafana_alert_notifications | to_nice_yaml }}
    dest: /etc/grafana/provisioning/notifiers/ansible.yml
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0640"
  notify: Restart grafana
  when: grafana_use_provisioning
