---
- name: Check which plugins are installed
  ansible.builtin.find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- name: Install plugins
  become: true
  become_user: "{{ grafana_user }}"
  ansible.builtin.command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins --repo {{ plugin_catalog_url }} plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - Restart grafana
  environment:
    http_proxy: "{{ http_proxy_dgfip }}"
    https_proxy: "{{ http_proxy_dgfip }}"
